### ISSUE TITLE
offhand and mainhand briefly appear when pressing LMB or RMB on empty main hand, mod configurations don't save

### ISSUE THREAD

**Issue by edl411** [ricksouth/serilum-mc-mods#1497]
## **Information**
Minecraft version: 1.19.2
Modloader: Fabric
Fabric loader version: 1.19.2
Environment: Singleplayer 

## **Description**
This is not an issue that occurred in 1.18.2, so this is rather peculiar. When I open the game, "Always Hide Main Hand" and "Always Hide Empty Main Hand" are toggled on, but in game, clicking left or right mouse button with an empty hand will cause both the main hand and the offhand to briefly appear on screen. Despite my numerous attempts to configure the options both in game and within Visual Studio Code, I have been unable to fix this problem on my own, as the config menu does not save. Even trying to set the options to "true" in Visual Studio Code does not work, as the code reverts itself for some strange reason, preventing me from making permanent changes even if I save. Again, I did not experience this issue in 1.18.2, so I am a bit confused.

**Comment by ricksouth** [comment]
This has been fixed in the latest version of Collective and Hide Hands. Thanks for opening the bug report and giving the mod a try!

https://www.curseforge.com/minecraft/mc-mods/collective/files
https://www.curseforge.com/minecraft/mc-mods/hide-hands/files

**Comment by edl411** [comment]
My empty hand still appears, but the issue with the mod's menu being unconfigurable has been fixed. Thank you!
