### ISSUE TITLE
Transcending Trident not launching me

### ISSUE THREAD

**Issue by AllOutJay** [ricksouth/serilum-mc-mods#1555]
## **Information**
Minecraft version: 1.19.3
Modloader: Fabric
Fabric loader version: 0.14.12
Environment: Multiplayer

Mod name: Transcending Trident
Mod version: 1.19.3-4.0
Config: Default out of the box config that is provide. True, 5, 3.0

## **Description**
When trying to launch myself with a riptide 3 trident and a water bucket in both hands while wearing an elytra, I am unable to launch myself off the ground. It instead only does the spiral on the ground and does not launch me like the example video on the mod page or like how using a riptide 3 trident in water behaves.

Additional Mods Installed:
collective-1.19.3-6.30
fabric-api-0.72.0+1.19.3
lithium-fabric-mc1.19.3-0.10.4
starlight-1.1.1+fabric.ae22326

## **Crash report**
N/A

**Comment by ricksouth** [comment]
Thanks for opening the issue and giving the mod a try! This has been fixed in version 4.2 of Transcending Trident.

https://www.curseforge.com/minecraft/mc-mods/transcending-trident

**Comment by AllOutJay** [comment]
Hi @ricksouth, I still appear to be running into the issue using the previously listed mods, but the most recent versions of collective and transcending trident. 

- transcendingtrident-1.19.3-4.2.jar
- collective-1.19.3-6.48.jar
- lithium-fabric-mc1.19.3-0.10.4.jar
- fabric-api-0.74.0+1.19.3.jar
- starlight-1.1.1+fabric.ae22326.jar

**Comment by gksjohn** [comment]
Still does not work—the latest patch and still not working.

**Comment by Magicrafter13** [comment]
Can confirm this still exists in the 1.20.x version of Transcending Tridents 4.2.

**Comment by SavageTheUnicorn** [comment]
This is in 1.19,4 version 4.2 aswell.

**Comment by AllOutJay** [comment]
Hi @ricksouth, is there any chance this will be fixed? It still doesn't work in the 1.21 versions.

**Comment by ImGreyCat** [comment]
> Hi @ricksouth, is there any chance this will be fixed? It still doesn't work in the 1.21 versions.

Did you try to put a water bucket in your offhand? If you didn't, try and it should work

**Comment by AllOutJay** [comment]
Yes @ImGreyCat. I followed exactly what was done in the gif/video attached to the mod page.

**Comment by elskeptico** [comment]
@ricksouth 1.5 years later, is this going to be fixed?

**Comment by allanonmage** [comment]
I put this in my Fabric 1.20.1 modpack because I thought it would be cool and enjoyed it in my 1.19.2 modpack, but it's not working in 2026 :(

Seems there were recent updates to the mod, but not for "older" versions :(

Server: https://moddermore.net/list/tRJW81cDgFPD
Client: https://moddermore.net/list/qZpNyAcupOl-
