### ISSUE TITLE
Releasing sneak makes mining normal speed, but still harvests full tree

### ISSUE THREAD

**Issue by James-Fire** [ricksouth/serilum-mc-mods#2126]
## **Information**
Minecraft version: 1.20.2
Modloader: Forge
Forge version: 48.1.0
Environment: Singleplayer

Mod name: Tree Harvester
Mod version: 8.4

## **Description**
I held down sneak to full chop a tree, and then released it. Mining time went back to normal, but it still full-chopped the tree.

**Comment by Fyoncle** [comment]
Yeah, a way to fix that would be when u release shift it would reset the whole progress.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 9.1 of Tree Harvester. Appreciate it.

https://curseforge.com/minecraft/mc-mods/tree-harvester/files

**Comment by Ozzuneoj** [comment]
> Thank you for opening the issue and giving the mod a try! This has been fixed in version 9.1 of Tree Harvester. Appreciate it.
> 
> https://curseforge.com/minecraft/mc-mods/tree-harvester/files

This issue seems to still exist in both Tree Harvester and Ore Harvester:
https://github.com/Serilum/.issue-tracker/issues/2511#issuecomment-2644549812
https://github.com/Serilum/.issue-tracker/issues/2757

I am experiencing it in 1.21.4 running Fabric.
