### ISSUE TITLE
Giving player an item via `/give` causes rendering duplication

### ISSUE THREAD

**Issue by TizzySaurus** [ricksouth/serilum-mc-mods#2224]
## **Information**
Minecraft version: 1.20.4
Modloader: Quilt
Quilt loader version: 0.24.0-beta.8 (with fabric api 0.96.3)
Environment: Singleplayer & Multiplayer

Mod name: Configurable Despawn Timer
Mod version: 3.4 (for MC 1.20.4)

## **Description**
Upon giving a player [seemingly] any item via the `/give` command, the item is given to the player but also drops on the floor (despite actually being in the player's inventory). Note that the 'dropped' item cannot be picked up, so this isn't actually duplicating the item.

This visual glitch persists across both rejoining the world (shown in video) and restarting the game. It also happens on multiple servers, although the video is from a singleplayer world.

Video: https://streamable.com/08bqnp

I only have Fabric API, Collective, and Configurable Despawn Timer active so don't think it's a bug caused by some other mod.

**Comment by ghost** [comment]
This is actually not just a 'rendering' item, but a duplicate drop that has the maximum pickup delay, I had it happening too and had to remove the duplicate with NBT Edtitor.

**Comment by James103** [comment]
If you stand on a hopper, look down, and run `/give @s stone_pickaxe`, does a stone pickaxe end up in your inventory **and in the hopper** (bold = unexpected)?

**Comment by ghost** [comment]
> If you stand on a hopper, look down, and run `/give @s stone_pickaxe`, does a stone pickaxe end up in your inventory **and in the hopper** (bold = unexpected)?

Yes it does, the hopper picks it up without any delay and I end up with one item in my inventory and a duplicate in the hopper.

**Comment by ghost** [comment]
I wanted to add that I overlooked this ticket being made with quilt as loader. What I typed was what happened testing on fabric. I have not tested this with quilt. However, I can confirm that this bug does NOT happen when the mod is loaded in forge.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 4.0 of Configurable Despawn Timer, alongside some other features that have been added! :)

https://curseforge.com/minecraft/mc-mods/configurable-despawn-timer/files

**Comment by valkyrienyanko** [comment]
The issue is still present in `Fabric 0.15.11`, `MC 1.20.1` for `configurabledespawntimer-1.20.1-4.0.jar`  
_(I'm not using Quilt. I'm just using Fabric)_

**Comment by ricksouth** [comment]
> The issue is still present in `Fabric 0.15.11`, `MC 1.20.1` for `configurabledespawntimer-1.20.1-4.0.jar` _(I'm not using Quilt. I'm just using Fabric)_

Ok this has _for sure_ been fixed in version 4.1 of the mod. But since I thought that before, please let me know if the issue persists. Thank you for the comment!

https://curseforge.com/minecraft/mc-mods/configurable-despawn-timer/files
