### ISSUE TITLE
Other players don't get kits

### ISSUE THREAD

**Issue by WordStormRose** [ricksouth/serilum-mc-mods#2279]
## **Information**
Minecraft version: 1.20.1
Modloader: Forge
Forge version: 47.2.19
Environment: Multiplayer

Mod name: Starter Kit
Mod version: 1.20.1-6.5

## **Description**
I have it set up so that the players on my server (or who use my modpack) can choose between five different kits; it works fantastic in singleplayer and for the person to log in on the server, but after that the gui doesn't show up for anyone, whether it's in a lan world or on my server. Other players can use the commands, but I'd much rather them be able to see the gui so they can better see what their options are.
I've tested both with my full modpack and with only the mods required for my custom starter kits to have most of their items.

**Comment by WordStormRose** [comment]
Update: it seems that there's only an issue when there's already a player on the server? One of my other smp members joined after a server restart when no-one else was on and got the gui, but any other time it's working how I said in my initial message.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 6.9 of Starter Kit.

https://www.curseforge.com/minecraft/mc-mods/starter-kit/files

**Comment by ZsoltMolnarrr** [comment]
This issue has resurfaced on SK 7.1 Fabric 1.21.1, tested myself.
According to reports from my players, Fabric 1.20.1 release has not been fixed either.

Could you please take a look again?

**Comment by My7terio** [comment]
The issue is still present in 7.4 on forge, when joining a server only the host gets to choose kit

**Comment by kthulugit** [comment]
Neoforge 1.21.1 version 7.4
When starting a new world with Essential Mod, only the host gets the GUI to pick a kit, nobody who joins afterward gets the GUI. They also cannot choose a kit using commands. Since Essential is a huge mod for multiplayer, it'd be nice if this could get looked at :)
