### ISSUE TITLE
Random item in inventory disappears after death

### ISSUE THREAD

**Issue by relitrix-archive** [ricksouth/serilum-mc-mods#2727]
## **Information**
Minecraft version: 1.21.1
Modloader: Fabric
Fabric loader version: 0.16.5
Environment: Multiplayer & Singleplayer

Mod name: Stack Refill
Mod version: 4.5

## **Description**
After death, a random item from the storage slot moves to the active slot and disappears shortly after respawn.

## **Video**

https://github.com/user-attachments/assets/d635ef92-cfec-4761-8f79-ad1c5a3dcfbc

**Comment by relitrix-archive** [comment]
It looks like there is a pattern: only a first singular item in order seems to be affected

**Comment by MinecartCopper** [comment]
I do not know WHY this has been reported in July (https://github.com/Serilum/.issue-tracker/issues/2502) and again in October.... and seems to be no movement that I can see?

Version for Minecraft 1.21.4 STILL has this. Any item in your inventory starting from the top left slot moving to the bottom right corner will be placed into the hot bar that you are actively on when you die. And when you click respawn that item is DELETED. So ABSOLUTELY ANYTHING in your inventory is at RISK of being LOST due to this BUG with this Mod. Until fixed, this mod is DELETED.

**Comment by Gitte96** [comment]
I am currently playing in 1.21.4 and I also have this issue. Just uninstalled the mod. I've already lost too much on this until I realised it was this mod that is causing the issue.

**Comment by ricksouth** [comment]
Thank you for opening the issue and giving the mod a try! This has been fixed in version 4.7 of Stack Refill. Apologies for the inconvenience caused. :\

https://www.curseforge.com/minecraft/mc-mods/stack-refill/files

**Comment by worm-from-future** [comment]
Still happening to me on 1.21.5 (mod version 4.7, latest from modrinth) @ricksouth
