### ISSUE TITLE
Errors in server log and client crash with collective-fabric-1.17.x-1.32.jar

### ISSUE THREAD

**Issue by GhostRiderGrey** [ricksouth/serilum-mc-mods#706]
## **Information**
Minecraft version: 1.17.1
Modloader: Fabric
Fabric loader version: fabric-api-0.40.1+1.17
Environment: Singleplayer / Multiplayer     Both...errors in serverlog and client crash with no report

Mod name: collective-fabric-1.17.x-1.32.jar
Mod version: 1.32

## **Description**
After moving from collective-fabric-1.17.x-1.30.jar to collective-fabric-1.17.x-1.32.jar I am getting errors in the server log and a client crash with no report generated.  Reverting to 1.30 resolves the issue.

## **Crash report**
This block is repeated several time in the server log:

[15:39:37] [Server thread/ERROR]: Failed to create block entity minecraft:mob_spawner
org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:1111) ~[?:?]
	at net.minecraft.class_2591$$Lambda$2514/0x0000000040b625f8.create(Unknown Source) ~[?:?]
	at net.minecraft.class_2591.method_11032(class_2591.java:84) ~[intermediary-server.jar:?]
	at net.minecraft.class_2586.method_17899(class_2586.java:79) [intermediary-server.jar:?]
	at net.minecraft.class_2586$$Lambda$7096/0x00000000433d52e8.apply(Unknown Source) [intermediary-server.jar:?]
	at java.util.Optional.map(Optional.java:260) [?:?]
	at net.minecraft.class_2586.method_11005(class_2586.java:77) [intermediary-server.jar:?]
	at net.minecraft.class_2852.method_12386(class_2852.java:378) [intermediary-server.jar:?]
	at net.minecraft.class_2852.method_12388(class_2852.java:137) [intermediary-server.jar:?]
	at net.minecraft.class_2852$$Lambda$6790/0x00000000427d5c40.accept(Unknown Source) [intermediary-server.jar:?]
	at net.minecraft.class_2818.method_12206(class_2818.java:505) [intermediary-server.jar:?]
	at net.minecraft.class_3898.method_17227(class_3898.java:618) [intermediary-server.jar:?]
	at net.minecraft.class_3898$$Lambda$7094/0x00000000433d4ed8.apply(Unknown Source) [intermediary-server.jar:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) [intermediary-server.jar:?]
	at com.mojang.datafixers.util.Either$$Lambda$6914/0x0000000042fcf288.apply(Unknown Source) [intermediary-server.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) [intermediary-server.jar:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) [intermediary-server.jar:?]
	at net.minecraft.class_3898.method_20460(class_3898.java:606) [intermediary-server.jar:?]
	at net.minecraft.class_3898$$Lambda$7047/0x0000000042ffcb28.apply(Unknown Source) [intermediary-server.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) [?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) [?:?]
	at net.minecraft.class_3900.method_17634(class_3900.java:58) [intermediary-server.jar:?]
	at net.minecraft.class_3900$$Lambda$6774/0x0000000042f582e8.run(Unknown Source) [intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) [intermediary-server.jar:?]
	at net.minecraft.class_3215$class_4212.method_18859(class_3215.java:528) [intermediary-server.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) [intermediary-server.jar:?]
	at net.minecraft.class_3215$class_4212.method_16075(class_3215.java:537) [intermediary-server.jar:?]
	at net.minecraft.class_3215.method_19492(class_3215.java:280) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:776) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) [intermediary-server.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3774(MinecraftServer.java:521) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:353) [intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3823(class_3176.java:184) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) [intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer$$Lambda$6640/0x00000000425e68a8.run(Unknown Source) [intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:883) [?:?]
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [collective_fabric.mixins.json:BaseSpawnerMixin] from phase [DEFAULT] in config [collective_fabric.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356) ~[fabric-server-launch.jar:?]
	... 44 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyVariable annotation on BaseSpawner_tick could not find any targets matching 'Lnet/minecraft/class_1917;serverTick()V' in net.minecraft.class_1917. Using refmap collective-fabric-1.17.x-refmap.json [PREINJECT Applicator Phase -> collective_fabric.mixins.json:BaseSpawnerMixin -> Prepare Injections ->  -> localvar$bgh000$BaseSpawner_tick(Lnet/minecraft/class_1297;)Lnet/minecraft/class_1297; -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.ModifyVariableInjectionInfo.<init>(ModifyVariableInjectionInfo.java:45) ~[fabric-server-launch.jar:?]
	at jdk.internal.reflect.GeneratedConstructorAccessor65.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
	... 44 more
[15:39:37] [Server thread/WARN]: Skipping BlockEntity with id minecraft:mob_spawner

**Comment by GhostRiderGrey** [comment]
[2021-09-19-1.log](https://github.com/ricksouth/serilum-mc-mods/files/7192480/2021-09-19-1.log)
Full log attached

**Comment by GhostRiderGrey** [comment]
Same errors and crash with 1.35

**Comment by ricksouth** [comment]
Thanks for submitting the bug report! I've just uploaded Collective-Fabric 1.36 which should fix the issue. Could you confirm that before I close it? Appreciate the help!

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/all

**Comment by GhostRiderGrey** [comment]
thanks ricksouth!  The server log is still showing the error with the mob spawner, but the client does now load instead of crashing.....so partially fixed?  lol

Current log attached using Collective-Fabric 1.36
[latest.log](https://github.com/ricksouth/serilum-mc-mods/files/7192533/latest.log)

**Comment by GhostRiderGrey** [comment]
Spoke too soon.  When the client tries to join the server, it does crash the server.  Server crash log attached
[crash-2021-09-19_10.01.45-server.txt](https://github.com/ricksouth/serilum-mc-mods/files/7192541/crash-2021-09-19_10.01.45-server.txt)
.

**Comment by ricksouth** [comment]
I can't seem to replicate it. Where are you running your client/server? E.g. external host, custom launcher?

**Comment by GhostRiderGrey** [comment]
Server and client are both running on the same machine (localhost)

**Comment by GhostRiderGrey** [comment]
Something to do with BaseSpawnerMixin?  I reverified that versions after collective-fabric-1.17.x-1.30  are giving me the issues

[10:59:13] [Server thread/FATAL]: Mixin apply failed collective_fabric.mixins.json:BaseSpawnerMixin -> net.minecraft.class_1917: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyVariable annotation on BaseSpawner_tick could not find any targets matching 'Lnet/minecraft/class_1917;serverTick()V' in net.minecraft.class_1917. Using refmap collective-fabric-1.17.x-refmap.json [PREINJECT Applicator Phase -> collective_fabric.mixins.json:BaseSpawnerMixin -> Prepare Injections ->  -> localvar$bha000$BaseSpawner_tick(Lnet/minecraft/class_1297;)Lnet/minecraft/class_1297; -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyVariable annotation on BaseSpawner_tick could not find any targets matching 'Lnet/minecraft/class_1917;serverTick()V' in net.minecraft.class_1917. Using refmap collective-fabric-1.17.x-refmap.json [PREINJECT Applicator Phase -> collective_fabric.mixins.json:BaseSpawnerMixin -> Prepare Injections ->  -> localvar$bha000$BaseSpawner_tick(Lnet/minecraft/class_1297;)Lnet/minecraft/class_1297; -> Parse]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:572) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:288) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:275) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:267) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.ModifyVariableInjectionInfo.<init>(ModifyVariableInjectionInfo.java:45) ~[fabric-server-launch.jar:?]
        at jdk.internal.reflect.GeneratedConstructorAccessor65.newInstance(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:140) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:624) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1247) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1033) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:388) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) [fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) [fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:1111) [?:?]
        at java.lang.Class.getDeclaredMethodsImpl(Native Method) [?:?]
        at java.lang.Class.getDeclaredMethods(Class.java:1173) [?:?]
        at java.lang.Class.getMethodSet(Class.java:1806) [?:?]
        at java.lang.Class.getMethods(Class.java:1732) [?:?]
        at java.lang.reflect.Proxy$ProxyBuilder.referencedTypes(Proxy.java:737) [?:?]
        at java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:643) [?:?]
        at java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:654) [?:?]
        at java.lang.reflect.Proxy.lambda$getProxyConstructor$0(Proxy.java:428) [?:?]
        at java.lang.reflect.Proxy$$Lambda$223/0x0000000000000000.apply(Unknown Source) [?:?]
        at jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) [?:?]
        at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) [?:?]
        at java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:426) [?:?]
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1028) [?:?]
        at dev.architectury.event.EventFactory.lambda$createEventResult$1(EventFactory.java:78) [architectury-2.5.27-fabric.jar:?]
        at dev.architectury.event.EventFactory$$Lambda$7488/0x0000000052a823a0.apply(Unknown Source) [architectury-2.5.27-fabric.jar:?]
        at dev.architectury.event.EventFactory$EventImpl.update(EventFactory.java:245) [architectury-2.5.27-fabric.jar:?]
        at dev.architectury.event.EventFactory$EventImpl.invoker(EventFactory.java:211) [architectury-2.5.27-fabric.jar:?]
        at net.minecraft.class_1948.redirect$zgo000$overrideNaturalSpawnCondition(class_1948.java:646) [intermediary-server.jar:?]
        at net.minecraft.class_1948.method_24930(class_1948.java:278) [intermediary-server.jar:?]
        at net.minecraft.class_1948.method_8663(class_1948.java:199) [intermediary-server.jar:?]
        at net.minecraft.class_1948.method_27821(class_1948.java:187) [intermediary-server.jar:?]
        at net.minecraft.class_3215.method_20801(class_3215.java:368) [intermediary-server.jar:?]
        at net.minecraft.class_3215$$Lambda$7337/0x0000000052a0fe00.accept(Unknown Source) [intermediary-server.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) [?:?]
        at net.minecraft.class_3215.method_14161(class_3215.java:355) [intermediary-server.jar:?]
        at net.minecraft.class_3215.method_12127(class_3215.java:324) [intermediary-server.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:372) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891) [intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:335) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer$$Lambda$6698/0x0000000052656ba0.run(Unknown Source) [intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:883) [?:?]
[10:59:13] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:895) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:335) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer$$Lambda$6698/0x0000000052656ba0.run(Unknown Source) [intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:883) [?:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:1111) ~[?:?]
        at java.lang.Class.getDeclaredMethodsImpl(Native Method) ~[?:?]
        at java.lang.Class.getDeclaredMethods(Class.java:1173) ~[?:?]
        at java.lang.Class.getMethodSet(Class.java:1806) ~[?:?]
        at java.lang.Class.getMethods(Class.java:1732) ~[?:?]
        at java.lang.reflect.Proxy$ProxyBuilder.referencedTypes(Proxy.java:737) ~[?:?]
        at java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:643) ~[?:?]
        at java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:654) ~[?:?]
        at java.lang.reflect.Proxy.lambda$getProxyConstructor$0(Proxy.java:428) ~[?:?]
        at java.lang.reflect.Proxy$$Lambda$223/0x0000000000000000.apply(Unknown Source) ~[?:?]
        at jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) ~[?:?]
        at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) ~[?:?]
        at java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:426) ~[?:?]
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1028) ~[?:?]
        at dev.architectury.event.EventFactory.lambda$createEventResult$1(EventFactory.java:78) ~[architectury-2.5.27-fabric.jar:?]
        at dev.architectury.event.EventFactory$$Lambda$7488/0x0000000052a823a0.apply(Unknown Source) ~[?:?]
        at dev.architectury.event.EventFactory$EventImpl.update(EventFactory.java:245) ~[architectury-2.5.27-fabric.jar:?]
        at dev.architectury.event.EventFactory$EventImpl.invoker(EventFactory.java:211) ~[architectury-2.5.27-fabric.jar:?]
        at net.minecraft.class_1948.redirect$zgo000$overrideNaturalSpawnCondition(class_1948.java:646) ~[intermediary-server.jar:?]
        at net.minecraft.class_1948.method_24930(class_1948.java:278) ~[intermediary-server.jar:?]
        at net.minecraft.class_1948.method_8663(class_1948.java:199) ~[intermediary-server.jar:?]
        at net.minecraft.class_1948.method_27821(class_1948.java:187) ~[intermediary-server.jar:?]
        at net.minecraft.class_3215.method_20801(class_3215.java:368) ~[intermediary-server.jar:?]
        at net.minecraft.class_3215$$Lambda$7337/0x0000000052a0fe00.accept(Unknown Source) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at net.minecraft.class_3215.method_14161(class_3215.java:355) ~[intermediary-server.jar:?]
        at net.minecraft.class_3215.method_12127(class_3215.java:324) ~[intermediary-server.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:372) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891) ~[intermediary-server.jar:?]
        ... 6 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [collective_fabric.mixins.json:BaseSpawnerMixin] from phase [DEFAULT] in config [collective_fabric.mixins.json] FAILED during APPLY
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:642) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:594) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:356) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
        at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-server-launch.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:1111) ~[?:?]
        at java.lang.Class.getDeclaredMethodsImpl(Native Method) ~[?:?]
        at java.lang.Class.getDeclaredMethods(Class.java:1173) ~[?:?]
        at java.lang.Class.getMethodSet(Class.java:1806) ~[?:?]
        at java.lang.Class.getMethods(Class.java:1732) ~[?:?]
        at java.lang.reflect.Proxy$ProxyBuilder.referencedTypes(Proxy.java:737) ~[?:?]
        at java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:643) ~[?:?]
        at java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:654) ~[?:?]
        at java.lang.reflect.Proxy.lambda$getProxyConstructor$0(Proxy.java:428) ~[?:?]
        at java.lang.reflect.Proxy$$Lambda$223/0x0000000000000000.apply(Unknown Source) ~[?:?]
        at jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329) ~[?:?]
        at jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205) ~[?:?]
        at java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:426) ~[?:?]
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1028) ~[?:?]
        at dev.architectury.event.EventFactory.lambda$createEventResult$1(EventFactory.java:78) ~[architectury-2.5.27-fabric.jar:?]
        at dev.architectury.event.EventFactory$$Lambda$7488/0x0000000052a823a0.apply(Unknown Source) ~[?:?]
        at dev.architectury.event.EventFactory$EventImpl.update(EventFactory.java:245) ~[architectury-2.5.27-fabric.jar:?]
        at dev.architectury.event.EventFactory$EventImpl.invoker(EventFactory.java:211) ~[architectury-2.5.27-fabric.jar:?]
        at net.minecraft.class_1948.redirect$zgo000$overrideNaturalSpawnCondition(class_1948.java:646) ~[intermediary-server.jar:?]
        at net.minecraft.class_1948.method_24930(class_1948.java:278) ~[intermediary-server.jar:?]
        at net.minecraft.class_1948.method_8663(class_1948.java:199) ~[intermediary-server.jar:?]
        at net.minecraft.class_1948.method_27821(class_1948.java:187) ~[intermediary-server.jar:?]
        at net.minecraft.class_3215.method_20801(class_3215.java:368) ~[intermediary-server.jar:?]
        at net.minecraft.class_3215$$Lambda$7337/0x0000000052a0fe00.accept(Unknown Source) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at net.minecraft.class_3215.method_14161(class_3215.java:355) ~[intermediary-server.jar:?]
        at net.minecraft.class_3215.method_12127(class_3215.java:324) ~[intermediary-server.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:372) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891) ~[intermediary-server.jar:?]
        ... 6 more

**Comment by ricksouth** [comment]
I think I found the problem! Let me upload a new version. Don't mind 1.37, it doesn't include the feature as a temp fix

**Comment by ricksouth** [comment]
Could you check version 1.38 for me?

https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files/all

**Comment by GhostRiderGrey** [comment]
1.38 appears to have resolved the errors and issues!!  Let me just say before you close the report that you've been a joy to work with.  I love your mods, and am grateful to see that you are bringing them over to the Fabric side.  Thank you!

**Comment by ricksouth** [comment]
Awesome! Appreciate you helping me :) Thanks for the kind words and I'm glad you like them! Just around a 100 fabric ports to go 😏.

Closing it. 🥳
