### ISSUE TITLE
Transcending Trident Is Not Working.

### ISSUE THREAD

**Issue by Epimyst** [ricksouth/serilum-mc-mods#859]
## **Information**
Minecraft version: 1.18.1
Modloader: Forge
Forge version: 39.0.0
Environment: Singleplayer/Multiplayer

Mod name: Transcending Trident (In The Vanilla Experience Modpack)
Mod version: 2.1

## **Description**
Mod is installed on the server & installed client side, Cannot use Riptide while holding water bucket, video in discord for reference.

**Comment by Epimyst** [comment]
Still hoping to see this fixed.

**Comment by madcaker** [comment]
I'm having the same issue as well unfortunately. Still not sure what could be causing this.

**Comment by Slarper** [comment]
I guess the reason is in the mixin [EntityMixin.java](https://github.com/ricksouth/serilum-mc-mods/blob/master/sources-fabric/Transcending%20Trident%20(Fabric)/src/main/java/com/natamus/transcendingtrident/fabric/mixin/EntityMixin.java)

It injects a method named "isInWaterOrRain" in Entity.java in Minecraft.
But actually in fabric this method's name is "isTouchingWaterOrRain"

**Comment by 4AC11** [comment]
I'm having this same issue on Forge. I initially assumed it was an incompatibility with Apotheosis, but it seems like the mod itself is just broken in 1.18.

**Comment by ricksouth** [comment]
> I guess the reason is in the mixin [EntityMixin.java](https://github.com/ricksouth/serilum-mc-mods/blob/master/sources-fabric/Transcending%20Trident%20(Fabric)/src/main/java/com/natamus/transcendingtrident/fabric/mixin/EntityMixin.java)
> 
> It injects a method named "isInWaterOrRain" in Entity.java in Minecraft. But actually in fabric this method's name is "isTouchingWaterOrRain"

I'm using the official Mojang Mappings, so the mixin is actually correct. Appreciate the thought though!

**Comment by ricksouth** [comment]
This has been fixed in version 2.5 of Transcending Trident. It was due to me not using unique mixin file names, which caused it to be overwritten as soon as another mod was installed. The latest version should work again. Apologies for the delay!

https://www.curseforge.com/minecraft/mc-mods/transcending-trident/files

**Comment by 4AC11** [comment]
This is still an issue on mod version 2.5 on 1.18.2. Riptide does not work at all, even when config to disable the requirement for water buckets is enabled. I'm not sure if testing was done solely on 1.19, but I'm hoping this can be fixed soon.

**Comment by 4AC11** [comment]
Is this any closer to getting fixed?

**Comment by ricksouth** [comment]
I don't know why the mod didn't work. It seemed to only affect 1.18 (1.16 and 1.19 worked) and only outside of the development environment. I've attempted a fix, and tested it, and it seemed to have worked. Don't ask me why! Thanks for the patience and letting me know. Please let me know if it's still not working. Appreciate it!

https://www.curseforge.com/minecraft/mc-mods/transcending-trident/files
