### ISSUE TITLE
World not generating properly witth Village Spawn Point (Fabric)

### ISSUE THREAD

**Issue by GitUser14975** [ricksouth/serilum-mc-mods#968]
Minecraft version: 1.18.2
Modloader: Fabric
Fabric loader version: 0.13.3
Environment: Singleplayer

Mod name: Village Spawn Point (Fabric)
Mod version: 1.8

Hi, I was playing on my modpack and I ran into an issue that happens only when Village Spawn Point mod is installed. When I'm trying to create a new world with this mod it generates very slowly. I've been stuck with 0% for around a minute. I also noticed that when creating a new world without the mod, I had 4 files in the region folder inside the world's folder, but with the mod, thousands of files are created. With 1% of the world created, I had 5 963 files already. Once I had 5 969 files the world started generating normally and I spawned in a village, but it took huge amount of time.

Here's a link to download the exported CurseForge profile with all the mods, configs and the generated world:
[https://www.mediafire.com/file/n2l3v15yl4dl7s2/ExportedProfile.zip/file](https://www.mediafire.com/file/n2l3v15yl4dl7s2/ExportedProfile.zip/file)

**Comment by ricksouth** [comment]
I've just released version 4.22 of Collective which should fix the problem you were having. Could you do another test with creating a new world? The effiency should have been improved by a lot.

https://www.curseforge.com/minecraft/mc-mods/collective-fabric

**Comment by GitUser14975** [comment]
> I've just released version 4.22 of Collective which should fix the problem you were having. Could you do another test with creating a new world? The effiency should have been improved by a lot.
> 
> https://www.curseforge.com/minecraft/mc-mods/collective-fabric

Seems to be working the same. I've installed the newest version of Collective (4.24).

**Comment by spoorn** [comment]
Same thing happening for me, still a problem with the latest versions of both Collective and Village Spawn Point (Fabric)

**Comment by James103** [comment]
> the latest versions of both Collective and Village Spawn Point (Fabric)

What are the exact version numbers and/or filenames for Minecraft, Fabric loader, Collective, and Village Spawn Point?

**Comment by spoorn** [comment]
> > the latest versions of both Collective and Village Spawn Point (Fabric)
> 
> What are the exact version numbers and/or filenames for Minecraft, Fabric loader, Collective, and Village Spawn Point?

Collective 1.18.x-4.26
Fabric Loader 0.13.3
Minecraft 1.18.2
Village Spawn Point 1.18.x-1.8

**Comment by 1ceSpark** [comment]
I have the same problem, world generation is ultra slow when village spawn point is enabled.
Minecraft 1.19
Fabric Loader 0.14.8
collective-fabric-1.19.x-4.27.jar
villagespawnpoint-fabric_1.19.x-2.0.jar

**Comment by tossrid** [comment]
Same here, same versions as above.

**Comment by ghost** [comment]
Same problem. same versions as above.

**Comment by ricksouth** [comment]
Thanks for giving the mod a try and opening the issue! This has been fixed in version 2.5 of Village Spawn Point, together with the latest Collective update. Will be online as soon as CurseForge approves the file.

https://www.curseforge.com/minecraft/mc-mods/village-spawn-point-fabric/files
https://www.curseforge.com/minecraft/mc-mods/collective-fabric/files
